<div class="nav-bar">
	<a class="cur" href="" target="_self">首页</a>
	<a href="" target="_self">最近更新</a>
	<a href="" target="_self">完结小说</a>
	<a href="" target="_self">连载小说</a>
	<a href="" target="_self">男生小说</a>
	<a href="" target="_self">女生小说</a>
	<a href="" target="_self">小说排行榜</a>
	<a href="" target="_self">作者大全</a>
	<a href="" target="_self">书库大全</a>
	<a class="nb-all" href="" target="_self">全部小说分类</a>
</div>