<div class="nav-hot-category">
	<strong>热门分类：</strong>
	<a href="">玄幻</a>
	<a href="">奇幻</a>
	<a href="">仙侠</a>
	<a href="">悬疑</a>
	<a href="">历史</a>
	<a href="">军事</a>
	<a href="">灵异</a>
	<a href="">现代言情</a>
	<a href="">穿越架空</a>
	<a href="">总裁豪门</a>
	<a href="">青春校园</a>
	<a href="">现代言情</a>
	<a href="">穿越架空</a>
	<a href="">总裁豪门</a>
	<a href="">青春校园</a>
	<a href="">现代言情</a>
	<a href="">穿越架空</a>
	<a href="">总裁豪门</a>
	<a href="">青春校园</a>
</div>